### ISSUE TITLE
bug: "The Safe SDK could not be initialized"

### ISSUE THREAD

**Issue by mattstam** [safe-global/safe-core-sdk#679]
## Prerequisites

- First, many thanks for taking part in the community and helping us improve. We appreciate that a lot.
- Support questions are better asked in our Discord chat: https://chat.safe.global/
- Please ensure the issue isn't already reported.

*Please delete the above section and the instructions in the sections below before submitting*

## Description

<img width="709" alt="image" src="https://github.com/safe-global/safe-core-sdk/assets/15695189/c86b9cfc-55e5-41d4-b200-f6362cd24b6a">

Error: The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up.

## Environment

- Safe Core SDK version: Unknown
- Safe contract version: v1.4.1
- Environment:
  - web app
  - tried on both Chrome and Firefox

## Steps to reproduce

1. Deploy a v1.4.1 Safe
2. Connect Safe via WalletConnect on the webapp
3. Attempt to sign

## Expected result

Owner can sign

## Additional context

browser console errors:
```
uncaught (in promise) Error: Unsupported chains. connect() optionalNamespaces, chains must be defined as "namespace:chainId" e.g. "eip155:1": {...} in the namespace key OR as an array of CAIP-2 chainIds e.g. eip155: { chains: ["eip155:1", "eip155:5"] }
    at hs.validateNamespaces (index.es.js:1:22632)
    at hs.isValidConnect (index.es.js:1:22459)
    at hs.onSessionProposeRequest (index.es.js:1:15540)
    at hs.onPairingCreated (index.es.js:1:21785)
    at EventEmitter.<anonymous> (index.es.js:1:28456)
    at EventEmitter.emit (events.js:158:1)
    at kt.pair (index.es.js:1:44439)
    at async index.tsx:48:9
 
Code 103: Error creating a SafeTransaction (The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up.)

Code 105: Error initializing the Safe Core SDK (F.safeDeploymentsVersions[m] is undefined)

Code 105: Error initializing the Safe Core SDK (Cannot read properties of undefined (reading 'safeMasterCopyVersion'))

[Spindl SDK] request failed TypeError: NetworkError when attempting to fetch resource.

F.safeDeploymentsVersions[m] is undefined
```

**Comment by dasanra** [comment]
Hey this issue should reported on https://github.com/safe-global/safe-wallet-web

Anyway, could you specify more details about:
 - Web environment (app.safe.global?)
 - Chain used for the deployment
 
 Thank you.

**Comment by dasanra** [comment]
It seems could be related to v1.4.1 smart contract support in the web interface. Should be fixed soon.

https://github.com/5afe/safe-support/issues/376

**Comment by felodelavallet** [comment]
I have the same error: 
The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up.

How did you solution??

**Comment by manuelfdpereira** [comment]
yeah got the same error on a polygon safe
The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and Up.
Can't even add new signers to the vault or do anything with it.

**Comment by mattstam** [comment]
@felodelavallet @manuelfdpereira what Safe version are you on?

@dasanra since it seems this bug is still around we should re-open the issue.

**Comment by dasanra** [comment]
This error is thrown by the web interface usually when it has troubles reading information from the RPC endpoint. It's not related to any bug in the Core SDK. Reloading the web app usually fixes this. The web team will change this error to be more explicit.

**Comment by ertemann** [comment]
I am still having this error and issue on a valid SAFE on bArtio berachain testnet. 

Brave browser, wallet balances load.
